global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bi-api'
    static_configs:
      - targets: ['bi-api:8000']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jm:9249']
    metrics_path: /metrics

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: /metrics
